---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - k8up.io
  resources:
  - backups
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - k8up.io
  resources:
  - backups/status
  verbs:
  - get
- apiGroups:
  - k8up.io
  resources:
  - schedules
  verbs:
  - get
  - list
  - watch
